Iter13
KorsakovPV/shortener pull request #13
Opened 2023-06-13 18:26 UTC by KorsakovPV

2023-06-16 09:46 UTC, arttet requested changes

2023-06-16 09:46 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	_, err = conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS short_url (id TEXT PRIMARY KEY, original_url TEXT NOT NULL UNIQUE);")
Please add indexes

2023-06-16 09:46 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +			errSelect := conn.QueryRow(context.Background(), "select id from short_url where original_url=$1", body).Scan(&id)
```
INSERT INTO dealer (user_id)
    SELECT id
    FROM rows
    RETURNING id;
```

2023-06-17 13:45 UTC, KorsakovPV commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	_, err = conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS short_url (id TEXT PRIMARY KEY, original_url TEXT NOT NULL UNIQUE);")
Если я создаю таблицу этой командой у меня автоматом создаются два индекса.

short_url_pkey это b-tree индекс он создается потому что у меня для id указона команда PRIMARY KEY 

https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-PRIMARY-KEYS

Adding a primary key will automatically create a unique B-tree index on the column or group of columns listed in the primary key, and will force the column(s) to be marked NOT NULL.

И для поля original_url тоже создается b-tree индекс short_url_original_url_key так как указан UNIQUE

https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-UNIQUE-CONSTRAINTS

Adding a unique constraint will automatically create a unique B-tree index on the column or group of columns listed in the constraint. A uniqueness restriction covering only some rows cannot be written as a unique constraint, but it is possible to enforce such a restriction by creating a unique.

Уникальность обеспечивается за счет создания индекса.

2023-06-17 15:04 UTC, KorsakovPV commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +			errSelect := conn.QueryRow(context.Background(), "select id from short_url where original_url=$1", body).Scan(&id)
У меня так не сработало. Так работает скорее всего на postgresql 9.2.4. Там где на stackoverflow Видел этот ответ обсуждали именно эту версию postgres. У меня PostgreSQL 15.3.

У меня сработало так 

INSERT INTO public.short_url (id, original_url) 
VALUES ('12', 'https://practicum.yandex.ru11') 
ON CONFLICT (original_url) 
DO UPDATE SET original_url=EXCLUDED.original_url 
RETURNING ID;

2023-06-20 18:43 UTC, arttet approved these changes

2023-06-20 18:43 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	}(conn, context.Background())
You should use `ctx` here

2023-06-20 18:43 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	conn, err := pgx.Connect(ctx, cfg.FlagDataBaseDSN)
You need to move this code from here.

2023-06-20 18:43 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +			"INSERT INTO short_url (id, original_url) VALUES($1, $2)", body[i].UUID, body[i].URL)
Could you please provide a plan for this query?

2023-06-20 18:43 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	conn, err := pgx.Connect(ctx, cfg.FlagDataBaseDSN)
You have to do it once.

2023-06-20 18:43 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	_, err = conn.Exec(context.Background(), "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";")
Can we solve our task without this?

2023-06-20 18:43 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	_, err = conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS short_url (id TEXT PRIMARY KEY, original_url TEXT NOT NULL UNIQUE);")
Are you sure about `TEXT`?

2023-06-20 18:43 UTC, arttet commented on cmd/shortener/storage/dbstorage/dbstorage.go
> +	_, err = conn.Exec(context.Background(), "CREATE TABLE IF NOT EXISTS short_url (id TEXT PRIMARY KEY, original_url TEXT NOT NULL UNIQUE);")
Please provide plans for your queries.
https://www.postgresql.org/docs/current/using-explain.html

2023-06-26 03:31 UTC, merged