Iter9
KorsakovPV/shortener pull request #9
Opened 2023-05-27 20:35 UTC by KorsakovPV

2023-06-04 16:04 UTC, arttet requested changes

2023-06-04 16:04 UTC, arttet commented on cmd/shortener/apiserver/apiserver.go
> +	"encoding/json"
Please change the layout of the project

2023-06-05 19:46 UTC, KorsakovPV commented on cmd/shortener/apiserver/apiserver.go
> +	"encoding/json"
Moved folder apiserver

2023-06-06 06:41 UTC, arttet approved these changes

2023-06-06 06:41 UTC, arttet commented on .github/workflows/golangci-lint.yml
> +name: golangci-lint
Thank you!

2023-06-06 06:41 UTC, arttet commented on cmd/shortener/gzip/gzip.go
> +package gzip
This package should be in internal

2023-06-06 06:41 UTC, arttet commented on cmd/shortener/gzip/gzip.go
> +	if statusCode < 300 {
This is a magic number

2023-06-06 06:41 UTC, arttet commented on cmd/shortener/logging/logging.go
> +func init() {
Sometimes is not good to initialize logger in `init`.

2023-06-06 06:41 UTC, arttet commented on cmd/shortener/storage/localstorage/localstorage.go
> +	"io"
Please sort imports into buckets

2023-06-06 06:41 UTC, arttet commented on cmd/shortener/storage/localstorage/localstorage.go
> +func (c *Consumer) ReadShortURL() (*[]ShortURL, error) {
It would be better if it is `[]*ShortURL`

2023-06-06 06:41 UTC, arttet commented on cmd/shortener/storage/localstorage/localstorage.go
> +	for _, url := range *urls {
Here we do copy our objects

2023-06-07 20:15 UTC, merged